QBShared = QBShared or {}
QBShared.VehicleHashes = {}

QBShared.Vehicles = {
	--- Compacts
	['tamworth'] = {
		['name'] = 'Wibbly Wobbly',
		['brand'] = 'Bean',
		['model'] = 'tamworth',
		['price'] = 2000,
		['category'] = 'compacts',
		['hash'] = `tamworth`,
		['shop'] = 'pdm',
	},
		['ajwar'] = {
		['name'] = 'AJWAR',
		['brand'] = 'Rune',
		['model'] = 'ajwar',
		['price'] = 6000,
		['category'] = 'compacts',
		['hash'] = `ajwar`,
		['shop'] = 'pdm',
	},
	['asbo'] = {
		['name'] = 'Asbo',
		['brand'] = 'Maxwell',
		['model'] = 'asbo',
		['price'] = 6000,
		['category'] = 'compacts',
		['hash'] = `asbo`,
		['shop'] = 'pdm',
	},
		['michelli'] = {
		['name'] = 'Michelli GT',
		['brand'] = 'Lampadati',
		['model'] = 'michelli',
		['price'] = 9110,
		['category'] = 'compacts',
		['hash'] = `michelli`,
		['shop'] = 'pdm',
	},
		['cheburek'] = {
		['name'] = 'Cheburek',
		['brand'] = 'Rune',
		['model'] = 'cheburek',
		['price'] = 6000,
		['category'] = 'compacts',
		['hash'] = `cheburek`,
		['shop'] = 'pdm',
	},
		['dynasty'] = {							--DLC
		['name'] = 'Dynasty',
		['brand'] = 'Weeny',
		['model'] = 'dynasty',
		['price'] = 4500,
		['category'] = 'compacts',
		['hash'] = `dynasty`,
		['shop'] = 'pdm',
	},
		['nebula'] = {							--DLC
		['name'] = 'Nebula',
		['brand'] = 'Vulcar',
		['model'] = 'nebula',
		['price'] = 6150,
		['category'] = 'compacts',
		['hash'] = `nebula`,
		['shop'] = 'pdm',
	},
		['retinue'] = {
		['name'] = 'Retinue',
		['brand'] = 'Vapid',
		['model'] = 'retinue',
		['price'] = 7850,
		['category'] = 'compacts',
		['hash'] = `retinue`,
		['shop'] = 'pdm',
	},
		['retinue2'] = {
		['name'] = 'Retinue MKII',
		['brand'] = 'Vapid',
		['model'] = 'retinue2',
		['price'] = 11805,
		['category'] = 'compacts',
		['hash'] = `retinue2`,
		['shop'] = 'pdm',
	},
	['blista'] = {
		['name'] = 'Blista',
		['brand'] = 'Dinka',
		['model'] = 'blista',
		['price'] = 6250,
		['category'] = 'compacts',
		['hash'] = `blista`,
		['shop'] = 'pdm',
	},
		['blista2'] = {
		['name'] = 'Blista Compact',
		['brand'] = 'Dinka',
		['model'] = 'blista2',
		['price'] = 6550,
		['category'] = 'compacts',
		['hash'] = `blista2`,
		['shop'] = 'pdm',
	},
		['futo'] = {
		['name'] = 'Futo',
		['brand'] = 'Karin',
		['model'] = 'futo',
		['price'] = 6130,
		['category'] = 'compacts',
		['hash'] = `futo`,
		['shop'] = 'pdm',
	},
		['warrener'] = {							--DLC +set sv_enforceGameBuild 2372
		['name'] = 'Warrener',
		['brand'] = 'Vulcar',
		['model'] = 'warrener',
		['price'] = 6000,
		['category'] = 'compacts',
		['hash'] = `warrener`,
		['shop'] = 'pdm',
	},
		['warrener2'] = {							--DLC +set sv_enforceGameBuild 2372
		['name'] = 'Warrener HKR',
		['brand'] = 'Vulcar',
		['model'] = 'warrener2',
		['price'] = 7250,
		['category'] = 'compacts',
		['hash'] = `warrener2`,
		['shop'] = 'pdm',
	},
		['brioso'] = {							--DLC +set sv_enforceGameBuild 2372
		['name'] = 'Grotti Brioso R/A',
		['brand'] = 'Grotti',
		['model'] = 'brioso',
		['price'] = 13250,
		['category'] = 'compacts',
		['hash'] = `brioso`,
		['shop'] = 'pdm',
	},
		['brioso2'] = {							--DLC +set sv_enforceGameBuild 2372
		['name'] = 'Grotti Brioso 300',
		['brand'] = 'Grotti',
		['model'] = 'brioso2',
		['price'] = 6250,
		['category'] = 'compacts',
		['hash'] = `brioso2`,
		['shop'] = 'pdm',
	},
		['club'] = {							--DLC +set sv_enforceGameBuild 2372
		['name'] = 'BF Club',
		['brand'] = 'BF',
		['model'] = 'club',
		['price'] = 12250,
		['category'] = 'compacts',
		['hash'] = `club`,
		['shop'] = 'pdm',
	},
		['dilettante'] = {							--DLC +set sv_enforceGameBuild 2372
		['name'] = 'Dilettante',
		['brand'] = 'Karin',
		['model'] = 'dilettante',
		['price'] = 5250,
		['category'] = 'compacts',
		['hash'] = `dilettante`,
		['shop'] = 'pdm',
	},
		['kanjo'] = {							--DLC +set sv_enforceGameBuild 2372
		['name'] = 'Blista Kanjo',
		['brand'] = 'Dinka',
		['model'] = 'kanjo',
		['price'] = 9250,
		['category'] = 'compacts',
		['hash'] = `kanjo`,
		['shop'] = 'pdm',
	},
		['panto'] = {							--DLC +set sv_enforceGameBuild 2372
		['name'] = 'Panto',
		['brand'] = 'Benefactor',
		['model'] = 'panto',
		['price'] = 6220,
		['category'] = 'compacts',
		['hash'] = `panto`,
		['shop'] = 'pdm',
	},
		['weevil'] = {							--DLC +set sv_enforceGameBuild 2372
		['name'] = 'Weevil',
		['brand'] = 'BF',
		['model'] = 'weevil',
		['price'] = 6150,
		['category'] = 'compacts',
		['hash'] = `weevil`,
		['shop'] = 'pdm',
	},
	['savestra'] = {
		['name'] = 'Savestra',
		['brand'] = 'Annis',
		['model'] = 'savestra',
		['price'] = 9900,
		['category'] = 'compacts',
		['hash'] = `savestra`,
		['shop'] = 'pdm',
	},
	-- Sedans --
	['asterope'] = {
		['name'] = 'Asterope',
		['brand'] = 'Karin',
		['model'] = 'asterope',
		['price'] = 21000,
		['category'] = 'sedans',
		['hash'] = `asterope`,
		['shop'] = 'pdm',
	},
	['cog55'] = {
		['name'] = 'Cognoscenti 55',
		['brand'] = 'Enus',
		['model'] = 'cog55',
		['price'] = 22000,
		['category'] = 'sedans',
		['hash'] = `cog55`,
		['shop'] = 'pdm',
	},
	['fugitive'] = {
		['name'] = 'Fugitive',
		['brand'] = 'Cheval',
		['model'] = 'fugitive',
		['price'] = 20000,
		['category'] = 'sedans',
		['hash'] = `fugitive`,
		['shop'] = 'pdm',
	},
	['primo2'] = {
		['name'] = 'Primo Custom',
		['brand'] = 'Albany',
		['model'] = 'primo2',
		['price'] = 21500,
		['category'] = 'sedans',
		['hash'] = `primo2`,
		['shop'] = 'pdm',
	},
	['schafter2'] = {
		['name'] = 'Schafter',
		['brand'] = 'Benefactor',
		['model'] = 'schafter2',
		['price'] = 26000,
		['category'] = 'sedans',
		['hash'] = `schafter2`,
		['shop'] = 'pdm',
	},
	['stafford'] = {							--DLC
		['name'] = 'Stafford',
		['brand'] = 'Enus',
		['model'] = 'stafford',
		['price'] = 18500,
		['category'] = 'sedans',
		['hash'] = `stafford`,
		['shop'] = 'pdm',
	},
	['stratum'] = {
		['name'] = 'Stratum',
		['brand'] = 'Zirconium',
		['model'] = 'stratum',
		['price'] = 19250,
		['category'] = 'sedans',
		['hash'] = `stratum`,
		['shop'] = 'pdm',
	},
	['superd'] = {
		['name'] = 'Super Diamond',
		['brand'] = 'Enus',
		['model'] = 'superd',
		['price'] = 18900,
		['category'] = 'sedans',
		['hash'] = `superd`,
		['shop'] = 'pdm',
	},
	['surge'] = {
		['name'] = 'Surge',
		['brand'] = 'Cheval',
		['model'] = 'surge',
		['price'] = 20000,
		['category'] = 'sedans',
		['hash'] = `surge`,
		['shop'] = 'pdm',
	},
	['buffalo2'] = {
		['name'] = 'Buffalo S',
		['brand'] = 'Bravado',
		['model'] = 'buffalo2',
		['price'] = 24500,
		['category'] = 'sedans',
		['hash'] = `buffalo2`,
		['shop'] = 'pdm',
	},
	['sultan'] = {
		['name'] = 'Sultan',
		['brand'] = 'Karin',
		['model'] = 'sultan',
		['price'] = 24500,
		['category'] = 'sedans',
		['hash'] = `sultan`,
		['shop'] = 'pdm',
	},
	-- Fast Sedans --
	['tailgater2'] = {							--DLC +set sv_enforceGameBuild 2372
		['name'] = 'Tailgater S',
		['brand'] = 'Obey',
		['model'] = 'tailgater2',
		['price'] = 52000,
		['category'] = 'sedans',
		['hash'] = `tailgater2`,
		['shop'] = 'pdm',
	},
	['komodafr'] = { 	 	--Vanilla Edit Mr Anderson
		['name'] = 'Komoda (R)',
		['brand'] = 'LAMPADATI',
		['model'] = 'komodafr',
		['price'] = 56000,
		['category'] = 'sedans',
		['hash'] = `komodafr`,
		['shop'] = 'pdm',
	},
	['kuruma'] = {
		['name'] = 'Kuruma',
		['brand'] = 'Karin',
		['model'] = 'kuruma',
		['price'] = 50500,
		['category'] = 'sedans',
		['hash'] = `kuruma`,
		['shop'] = 'pdm',
	},
	['jugular'] = {							--DLC
		['name'] = 'Jugular',
		['brand'] = 'Ocelot',
		['model'] = 'jugular',
		['price'] = 68000,
		['category'] = 'sedans',
		['hash'] = `jugular`,
		['shop'] = 'pdm',
	},
	['schafter3'] = {
		['name'] = 'Schafter V12',
		['brand'] = 'Benefactor',
		['model'] = 'schafter3',
		['price'] = 65000,
		['category'] = 'sedans',
		['hash'] = `schafter3`,
		['shop'] = 'pdm',
	},
	['sugoi'] = {
		['name'] = 'Sugoi',
		['brand'] = 'Dinka',
		['model'] = 'sugoi',
		['price'] = 59500,
		['category'] = 'sedans',
		['hash'] = `sugoi`,
		['shop'] = 'pdm',
	},
	['sultan2'] = {
		['name'] = 'Sultan Custom',
		['brand'] = 'Karin',
		['model'] = 'sultan2',
		['price'] = 57000,
		['category'] = 'sedans',
		['hash'] = `sultan2`,
		['shop'] = 'pdm',
	},
	['vstr'] = {
		['name'] = 'V-STR',
		['brand'] = 'Albany',
		['model'] = 'vstr',
		['price'] = 66000,
		['category'] = 'sedans',
		['hash'] = `vstr`,
		['shop'] = 'pdm',
	},
	['revolter'] = {
		['name'] = 'Revolter',
		['brand'] = 'Ubermacht',
		['model'] = 'revolter',
		['price'] = 65000,
		['category'] = 'sedans',
		['hash'] = `revolter`,
		['shop'] = 'pdm',
	},
	-- SUV --
	['baller'] = {
		['name'] = 'Baller',
		['brand'] = 'Gallivanter',
		['model'] = 'baller',
		['price'] = 42000,
		['category'] = 'suvs',
		['hash'] = `baller`,
		['shop'] = 'pdm',
	},
	['baller2'] = {
		['name'] = 'Baller',
		['brand'] = 'Gallivanter',
		['model'] = 'baller2',
		['price'] = 45000,
		['category'] = 'suvs',
		['hash'] = `baller2`,
		['shop'] = 'pdm',
	},
	['baller3'] = {
		['name'] = 'Baller LE',
		['brand'] = 'Gallivanter',
		['model'] = 'baller3',
		['price'] = 56500,
		['category'] = 'suvs',
		['hash'] = `baller3`,
		['shop'] = 'pdm',
	},
	['bjxl'] = {
		['name'] = 'BeeJay XL',
		['brand'] = 'Karin',
		['model'] = 'bjxl',
		['price'] = 43000,
		['category'] = 'suvs',
		['hash'] = `bjxl`,
		['shop'] = 'pdm',
	},
	['dubsta'] = {
		['name'] = 'Dubsta',
		['brand'] = 'Benefactor',
		['model'] = 'dubsta',
		['price'] = 66000,
		['category'] = 'suvs',
		['hash'] = `dubsta`,
		['shop'] = 'pdm',
	},
	['granger'] = {
		['name'] = 'Granger',
		['brand'] = 'Declasse',
		['model'] = 'granger',
		['price'] = 40000,
		['category'] = 'suvs',
		['hash'] = `granger`,
		['shop'] = 'pdm',
	},
	['huntley'] = {
		['name'] = 'Huntley S',
		['brand'] = 'Enus',
		['model'] = 'huntley',
		['price'] = 38000,
		['category'] = 'suvs',
		['hash'] = `huntley`,
		['shop'] = 'pdm',
	},
	['landstalker2'] = {
		['name'] = 'Landstalker XL',
		['brand'] = 'Dundreary',
		['model'] = 'landstalker2',
		['price'] = 51000,
		['category'] = 'suvs',
		['hash'] = `landstalker2`,
		['shop'] = 'pdm',
	},
	['novak'] = {							--DLC
		['name'] = 'Novak',
		['brand'] = 'Lampadati',
		['model'] = 'novak',
		['price'] = 62000,
		['category'] = 'suvs',
		['hash'] = `novak`,
		['shop'] = 'pdm',
	},
	['patriot'] = {
		['name'] = 'Patriot',
		['brand'] = 'Mammoth',
		['model'] = 'patriot',
		['price'] = 55000,
		['category'] = 'suvs',
		['hash'] = `patriot`,
		['shop'] = 'pdm',
	},
	['rebla'] = {
		['name'] = 'Rebla GTS',
		['brand'] = 'Übermacht',
		['model'] = 'rebla',
		['price'] = 51000,
		['category'] = 'suvs',
		['hash'] = `rebla`,
		['shop'] = 'pdm',
	},
	['seminole2'] = {
		['name'] = 'Seminole Frontier',
		['brand'] = 'Canis',
		['model'] = 'seminole2',
		['price'] = 48000,
		['category'] = 'suvs',
		['hash'] = `seminole2`,
		['shop'] = 'pdm',
	},
	['toros'] = {							--DLC
		['name'] = 'Toros',
		['brand'] = 'Pegassi',
		['model'] = 'toros',
		['price'] = 68000,
		['category'] = 'suvs',
		['hash'] = `toros`,
		['shop'] = 'pdm',
	},
	['xls'] = {
		['name'] = 'XLS',
		['brand'] = 'Benefactor',
		['model'] = 'xls',
		['price'] = 52000,
		['category'] = 'suvs',
		['hash'] = `xls`,
		['shop'] = 'pdm',
	},
	['hellion'] = {							--DLC
		['name'] = 'Hellion',
		['brand'] = 'Annis',
		['model'] = 'hellion',
		['price'] = 64000,
		['category'] = 'suvs',
		['hash'] = `hellion`,
		['shop'] = 'pdm',
	},
	['contenderc'] = { 	 	-- Vanilla Edit Mr Anderson
		['name'] = 'Contender (C)',
		['brand'] = 'Vapid',
		['model'] = 'contenderc',
		['price'] = 77000,
		['category'] = 'suvs',
		['hash'] = `contenderc`,
		['shop'] = 'luxury',
	 },
	['patriots'] = { 	 	-- Vanilla Edit Mr Anderson
		['name'] = 'Patriot (S)',
		['brand'] = 'Mammoth',
		['model'] = 'patriots',
		['price'] = 69000,
		['category'] = 'suvs',
		['hash'] = `patriots`,
		['shop'] = 'luxury',
	 },
	-- Sport --
	['pentrogpr'] = { 	 	-- Vanilla Edit Mr Anderson
		['name'] = 'Pentro (GPR)',
		['brand'] = 'MAIBATSU',
		['model'] = 'pentrogpr',
		['price'] = 221000,
		['category'] = 'sports',
		['hash'] = `pentrogpr`,
		['shop'] = 'pdm',
	 },
	['cogcabrio'] = {
		['name'] = 'Cognoscenti Cabrio',
		['brand'] = 'Enus',
		['model'] = 'cogcabrio',
		['price'] = 130000,
		['category'] = 'sports',
		['hash'] = `cogcabrio`,
		['shop'] = 'pdm',
	},
	['carbonizzare'] = {
		['name'] = 'Carbonizzare',
		['brand'] = 'Grotti',
		['model'] = 'carbonizzare',
		['price'] = 150000,
		['category'] = 'sports',
		['hash'] = `carbonizzare`,
		['shop'] = 'pdm',
	},
	['jester4'] = {
		['name'] = 'Jester Classic',
		['brand'] = 'Dinka',
		['model'] = 'jester4',
		['price'] = 145000,
		['category'] = 'sports',
		['hash'] = `jester4`,
		['shop'] = 'pdm',
	},
	['michelli'] = {
		['name'] = 'Michelli GT',
		['brand'] = 'Lampadati',
		['model'] = 'michelli',
		['price'] = 130000,
		['category'] = 'sports',
		['hash'] = `michelli`,
		['shop'] = 'pdm',
	},
	['monroe'] = {
		['name'] = 'Monroe',
		['brand'] = 'Pegassi',
		['model'] = 'monroe',
		['price'] = 175000,
		['category'] = 'sports',
		['hash'] = `monroe`,
		['shop'] = 'pdm',
	},
	['rapidgt3'] = {
		['name'] = 'Rapid GT',
		['brand'] = 'Dewbauchee',
		['model'] = 'rapidgt3',
		['price'] = 190000,
		['category'] = 'sports',
		['hash'] = `rapidgt3`,
		['shop'] = 'pdm',
	},
	['zion3'] = {					--DLC
		['name'] = 'Zion Classic',
		['brand'] = 'Übermacht',
		['model'] = 'zion3',
		['price'] = 145000,
		['category'] = 'sports',
		['hash'] = `zion3`,
		['shop'] = 'pdm',
	},
	['banshee'] = {
		['name'] = 'Banshee',
		['brand'] = 'Bravado',
		['model'] = 'banshee',
		['price'] = 196000,
		['category'] = 'sports',
		['hash'] = `banshee`,
		['shop'] = 'pdm',
	},
	['calico'] = {					--DLC +set sv_enforceGameBuild 2372
		['name'] = 'Calico GTF',
		['brand'] = 'Karin',
		['model'] = 'calico',
		['price'] = 193000,
		['category'] = 'sports',
		['hash'] = `calico`,
		['shop'] = 'pdm',
	},
		['comet'] = {						
		['name'] = 'Comet',
		['brand'] = 'Pfister',
		['model'] = 'comet',
		['price'] = 180000,
		['category'] = 'sports',
		['hash'] = `comet`,
		['shop'] = 'pdm',
	},
		['comet3'] = {
		['name'] = 'Comet Retro Custom',
		['brand'] = 'Pfister',
		['model'] = 'comet3',
		['price'] = 182000,
		['category'] = 'sports',
		['hash'] = `comet3`,
		['shop'] = 'pdm',
	},
		['comet5'] = {
		['name'] = 'Comet SR',
		['brand'] = 'Pfister',
		['model'] = 'comet5',
		['price'] = 212000,
		['category'] = 'sports',
		['hash'] = `comet5`,
		['shop'] = 'pdm',
	},
		['coquette'] = {
		['name'] = 'Coquette',
		['brand'] = 'Invetero',
		['model'] = 'coquette',
		['price'] = 202000,
		['category'] = 'sports',
		['hash'] = `coquette`,
		['shop'] = 'pdm',
	},
		['cypher'] = {				-- DLC +set sv_enforceGameBuild 2372
		['name'] = 'Cypher',
		['brand'] = 'Ubermacht',
		['model'] = 'cypher',
		['price'] = 212000,
		['category'] = 'sports',
		['hash'] = `cypher`,
		['shop'] = 'pdm',
	},
		['drafter'] = {							--DLC
		['name'] = '8F Drafter',
		['brand'] = 'Obey',
		['model'] = 'drafter',
		['price'] = 220000,
		['category'] = 'sports',
		['hash'] = `drafter`,
		['shop'] = 'pdm',
	},
		['elegy'] = {							--DLC
		['name'] = 'Elegy Retro Custom',
		['brand'] = 'Annis',
		['model'] = 'elegy',
		['price'] = 222000,
		['category'] = 'sports',
		['hash'] = `elegy`,
		['shop'] = 'pdm',
	},
	['elegy2'] = {
		['name'] = 'Elegy RH8',
		['brand'] = 'Annis',
		['model'] = 'elegy2',
		['price'] = 221000,
		['category'] = 'sports',
		['hash'] = `elegy2`,
		['shop'] = 'pdm',
	},
		['euros'] = {			--	DLC +set sv_enforceGameBuild 2372
		['name'] = 'Euros',
		['brand'] = 'Annis',
		['model'] = 'euros',
		['price'] = 210000,
		['category'] = 'sports',
		['hash'] = `euros`,
		['shop'] = 'pdm',
	},
		['feltzer2'] = {
		['name'] = 'Feltzer',
		['brand'] = 'Benefactor',
		['model'] = 'feltzer2',
		['price'] = 197000,
		['category'] = 'sports',
		['hash'] = `feltzer2`,
		['shop'] = 'pdm',
	},
		['imorgon'] = {
		['name'] = 'Imorgon',
		['brand'] = 'Overflod',
		['model'] = 'imorgon',
		['price'] = 212000,
		['category'] = 'sports',
		['hash'] = `imorgon`,
		['shop'] = 'pdm',
	},
		['issi7'] = {						--	DLC
		['name'] = 'Issi sports',
		['brand'] = 'Weeny',
		['model'] = 'issi7',
		['price'] = 180000,
		['category'] = 'sports',
		['hash'] = `issi7`,
		['shop'] = 'pdm',
	},
		['penumbra2'] = {
		['name'] = 'Penumbra FF',
		['brand'] = 'Maibatsu',
		['model'] = 'penumbra2',
		['price'] = 182000,
		['category'] = 'sports',
		['hash'] = `penumbra2`,
		['shop'] = 'pdm',
	},
		['remus'] = {						--LC +set sv_enforceGameBuild 2372
		['name'] = 'Remus',
		['brand'] = 'Annis',
		['model'] = 'remus',
		['price'] = 181000,
		['category'] = 'sports',
		['hash'] = `remus`,
		['shop'] = 'pdm',
	},
		['rt3000'] = {				--	DLC +set sv_enforceGameBuild 2372
		['name'] = 'RT3000',
		['brand'] = 'Dinka',
		['model'] = 'rt3000',
		['price'] = 215000,
		['category'] = 'sports',
		['hash'] = `rt3000`,
		['shop'] = 'pdm',
	},
		['sentinel3'] = {
		['name'] = 'Sentinel Classic',
		['brand'] = 'Übermacht',
		['model'] = 'sentinel3',
		['price'] = 187000,
		['category'] = 'sports',
		['hash'] = `sentinel3`,
		['shop'] = 'pdm',
	},
		['sultan3'] = {					--DLC +set sv_enforceGameBuild 2372
		['name'] = 'Sultan Classic Custom',
		['brand'] = 'Karin',
		['model'] = 'sultan3',
		['price'] = 175000,
		['category'] = 'sports',
		['hash'] = `sultan3`,
		['shop'] = 'pdm',
	},
		['vectre'] = {					--DLC +set sv_enforceGameBuild 2372
		['name'] = 'Emperor Vectre',
		['brand'] = 'Emperor',
		['model'] = 'vectre',
		['price'] = 211000,
		['category'] = 'sports',
		['hash'] = `vectre`,
		['shop'] = 'pdm',
	},
		['zr350'] = {					--DLC +set sv_enforceGameBuild 2372
		['name'] = 'ZR350',
		['brand'] = 'Annis',
		['model'] = 'zr350',
		['price'] = 182000,
		['category'] = 'sports',
		['hash'] = `zr350`,
		['shop'] = 'pdm',
	},
		['sultanrs'] = {
		['name'] = 'Sultan RS',
		['brand'] = 'Karin',
		['model'] = 'sultanrs',
		['price'] = 176500,
		['category'] = 'sports',
		['hash'] = `sultanrs`,
		['shop'] = 'pdm',
	},
		['argento'] = { 	 	-- Vanilla Edit Mr Anderson
		['name'] = 'Argento',
		['brand'] = 'Obey',
		['model'] = 'argento',
		['price'] = 221000,
		['category'] = 'sedan',
		['hash'] = `argento`,
		['shop'] = 'pdm',
	},
		['asteropers'] = { 	 	-- Vanilla Edit Mr Anderson
		['name'] = 'Asteropers',
		['brand'] = 'Karin',
		['model'] = 'asteropers',
		['price'] = 221000,
		['category'] = 'sedan',
		['hash'] = `asteropers`,
		['shop'] = 'pdm',
	},
		['citi'] = { 	 	-- Vanilla Edit Mr Anderson
		['name'] = 'Citi',
		['brand'] = 'Dinka',
		['model'] = 'citi',
		['price'] = 175000,
		['category'] = 'sports',
		['hash'] = `citi`,
		['shop'] = 'pdm',
	},
		['cometrwt'] = { 	 	-- Vanilla Edit Mr Anderson
		['name'] = 'Comet (R)',
		['brand'] = 'PFISTER',
		['model'] = 'cometrwt',
		['price'] = 221000,
		['category'] = 'sports',
		['hash'] = `cometrwt`,
		['shop'] = 'pdm',
	},
	 ['coqgte'] = { 	 	-- Vanilla Edit Mr Anderson
		['name'] = 'Coquette (GT)',
		['brand'] = 'Inverto',
		['model'] = 'coqgte',
		['price'] = 221000,
		['category'] = 'sports',
		['hash'] = `coqgte`,
		['shop'] = 'pdm',
	},
	 ['cypherct'] = { 	 	-- Vanilla Edit Mr Anderson
		['name'] = 'Cypher (GT)',
		['brand'] = 'Ubermacht',
		['model'] = 'cypherct',
		['price'] = 221000,
		['category'] = 'sports',
		['hash'] = `cypherct`,
		['shop'] = 'pdm',
	},
		['deluxogt'] = { 	 	-- Vanilla Edit Mr Anderson
		['name'] = 'Deluxo (GT)',
		['brand'] = 'IMPONTE',
		['model'] = 'deluxogt',
		['price'] = 221000,
		['category'] = 'sports',
		['hash'] = `deluxogt`,
		['shop'] = 'pdm',
	},
		['draftgpr'] = { 	 	-- Vanilla Edit Mr Anderson
		['name'] = 'Drafter (GPR)',
		['brand'] = 'Obey',
		['model'] = 'draftgpr',
		['price'] = 221000,
		['category'] = 'sports',
		['hash'] = `draftgpr`,
		['shop'] = 'pdm',
	 },
		['elegyrh7'] = { 	 	-- Vanilla Edit Mr Anderson
		['name'] = 'Elegy RH7',
		['brand'] = 'Annis',
		['model'] = 'elegyrh7',
		['price'] = 221000,
		['category'] = 'sports',
		['hash'] = `elegyrh7`,
		['shop'] = 'pdm',
	 },
		['elegyrh8wide'] = { 	 	-- Vanilla Edit Mr Anderson
		['name'] = 'Elegy RH8 (W)',
		['brand'] = 'Annis',
		['model'] = 'elegyrh8wide',
		['price'] = 221000,
		['category'] = 'sports',
		['hash'] = `elegyrh8wide`,
		['shop'] = 'pdm',
	 },
		['elegysanshi'] = { 	 	-- Vanilla Edit Mr Anderson
		['name'] = 'Elegy Sanshi',
		['brand'] = 'Annis',
		['model'] = 'elegysanshi',
		['price'] = 221000,
		['category'] = 'sports',
		['hash'] = `elegysanshi`,
		['shop'] = 'pdm',
	 },
		['elegyx'] = { 	 	-- Vanilla Edit Mr Anderson
		['name'] = 'Elegy X',
		['brand'] = 'Annis',
		['model'] = 'elegyx',
		['price'] = 221000,
		['category'] = 'sports',
		['hash'] = `elegyx`,
		['shop'] = 'pdm',
	 },
		['furzen'] = { 	 	-- Vanilla Edit Mr Anderson
		['name'] = 'Furzen',
		['brand'] = 'BF',
		['model'] = 'furzen',
		['price'] = 198000,
		['category'] = 'sports',
		['hash'] = `furzen`,
		['shop'] = 'pdm',
	 },
		['fusiladev8'] = { 	 	-- Vanilla Edit Mr Anderson
		['name'] = 'Fusilade V8',
		['brand'] = 'SCHYSTER',
		['model'] = 'fusiladev8',
		['price'] = 198000,
		['category'] = 'sports',
		['hash'] = `fusiladev8`,
		['shop'] = 'pdm', 
	 },
		['hachurac'] = { 	 	-- Vanilla Edit Mr Anderson
		['name'] = 'Hachura (C)',
		['brand'] = 'VULCAR',
		['model'] = 'hachurac',
		['price'] = 221000,
		['category'] = 'sports',
		['hash'] = `hachurac`,
		['shop'] = 'pdm',
	 },
		['jestgpr'] = { 	 	-- Vanilla Edit Mr Anderson
		['name'] = 'Jester (GPR)',
		['brand'] = 'DINKA',
		['model'] = 'jestgpr',
		['price'] = 221000,
		['category'] = 'sports',
		['hash'] = `jestgpr`,
		['shop'] = 'pdm',
	 },
		 ['jester5'] = { 	 	-- Vanilla Edit Mr Anderson
		['name'] = 'Jester Classic',
		['brand'] = 'DINKA',
		['model'] = 'jester5',
		['price'] = 198000,
		['category'] = 'sports',
		['hash'] = `jester5`,
		['shop'] = 'pdm',
	 },
		['komodafr'] = { 	 	-- Vanilla Edit Mr Anderson
		['name'] = 'Komoda (R)',
		['brand'] = 'LAMPADATI',
		['model'] = 'komodafr',
		['price'] = 221000,
		['category'] = 'sports',
		['hash'] = `komodafr`,
		['shop'] = 'pdm',
	 },
		['lynxgpr'] = { 	 	-- Vanilla Edit Mr Anderson
		['name'] = 'Lynx (GPR)',
		['brand'] = 'OCELOT',
		['model'] = 'lynxgpr',
		['price'] = 221000,
		['category'] = 'sports',
		['hash'] = `lynxgpr`,
		['shop'] = 'pdm',
	 },
		 ['niner'] = { 	 	-- Vanilla Edit Mr Anderson
		['name'] = 'Ninef (S)',
		['brand'] = 'Obey',
		['model'] = 'niner',
		['price'] = 221000,
		['category'] = 'sports',
		['hash'] = `niner`,
		['shop'] = 'pdm',
	 },
		 ['ninef'] = { 	 	-- Vanilla Edit Mr Anderson
		['name'] = 'Ninef',
		['brand'] = 'Obey',
		['model'] = 'ninef',
		['price'] = 221000,
		['category'] = 'sports',
		['hash'] = `ninef`,
		['shop'] = 'pdm',
	 },
		['ninef3'] = { 	 	-- Vanilla Edit Mr Anderson
		['name'] = 'Ninef (R)',
		['brand'] = 'Obey',
		['model'] = 'ninef3',
		['price'] = 221000,
		['category'] = 'sports',
		['hash'] = `ninef3`,
		['shop'] = 'pdm',
	 },
		['paragonxr'] = { 	 	-- Vanilla Edit Mr Anderson
		['name'] = 'Paragon (XR)',
		['brand'] = 'ENUS',
		['model'] = 'paragonxr',
		['price'] = 221000,
		['category'] = 'sports',
		['hash'] = `paragonxr`,
		['shop'] = 'pdm',
	 },
		['pentro'] = { 	 	-- Vanilla Edit Mr Anderson
		['name'] = 'Pentro',
		['brand'] = 'MAIBATSU',
		['model'] = 'pentro',
		['price'] = 221000,
		['category'] = 'sports',
		['hash'] = `pentro`,
		['shop'] = 'pdm',
	 },
		['reagpr'] = { 	 	-- Vanilla Edit Mr Anderson
		['name'] = 'Reaper (GPR)',
		['brand'] = 'PEGASSI',
		['model'] = 'reagpr',
		['price'] = 221000,
		['category'] = 'sports',
		['hash'] = `reagpr`,
		['shop'] = 'pdm',
	 },
	 	['requiemzr1'] = { 	 	-- Vanilla Edit Mr Anderson
		 ['name'] = 'ZR355',
		 ['brand'] = 'ANNIS',
		 ['model'] = 'requiemzr1',
		 ['price'] = 221000,
		 ['category'] = 'sports',
		 ['hash'] = `requiemzr1`, 
		 ['shop'] = 'pdm',
     },
	 	['requiemzr3'] = { 	 	-- Vanilla Edit Mr Anderson
		 ['name'] = 'ZR356',
		 ['brand'] = 'ANNIS',
		 ['model'] = 'requiemzr3',
		 ['price'] = 221000,
		 ['category'] = 'sports',
		 ['hash'] = `requiemzr3`, 
		 ['shop'] = 'pdm',
	 },
	 ['Revolutionw'] = { 	 	-- Vanilla Edit Mr Anderson
		 ['name'] = 'Revolution (S)',
		 ['brand'] = 'KARIN',
		 ['model'] = 'Revolutionw',
		 ['price'] = 221000,
		 ['category'] = 'sports',
		 ['hash'] = `Revolutionw`,
		 ['shop'] = 'pdm',
	 },
	 ['schwarzer2'] = { 	 	-- Vanilla Edit Mr Anderson
		 ['name'] = 'Schwarzer (S)',
		 ['brand'] = 'Ubermacht',
		 ['model'] = 'schwarzer2',
		 ['price'] = 221000,
		 ['category'] = 'sports',
		 ['hash'] = `schwarzer2`,
		 ['shop'] = 'pdm',
	 },
	 ['sentinelc'] = { 	 	-- Vanilla Edit Mr Anderson
		 ['name'] = 'Sentinel (C)',
		 ['brand'] = 'UBERMACH',
		 ['model'] = 'sentinelc',
		 ['price'] = 221000,
		 ['category'] = 'sports',
		 ['hash'] = `sentinelc`,
		 ['shop'] = 'pdm',
	 },
	 ['stratumc'] = { 	 	-- Vanilla Edit Mr Anderson
		 ['name'] = 'Stratum (C)',
		 ['brand'] = 'UBERMACH',
		 ['model'] = 'stratumc',
		 ['price'] = 221000,
		 ['category'] = 'sports',
		 ['hash'] = `stratumc`,
		 ['shop'] = 'pdm',
	 },
	 ['sultan2c'] = { 	 	-- Vanilla Edit Mr Anderson
		 ['name'] = 'Sultan (C)',
		 ['brand'] = 'KARIN',
		 ['model'] = 'sultan2c',
		 ['price'] = 221000,
		 ['category'] = 'sports',
		 ['hash'] = `sultan2c`,
		 ['shop'] = 'pdm',
	 },
	 ['tempesta2'] = { 	 	-- Vanilla Edit Mr Anderson
		 ['name'] = 'Tempesta (GT)',
		 ['brand'] = 'PEGASSI',
		 ['model'] = 'tempesta2',
		 ['price'] = 251000,
		 ['category'] = 'sports',
		 ['hash'] = `tempesta2`,
		 ['shop'] = 'pdm',
	 },
		 ['tempestaes'] = { 	 	-- Vanilla Edit Mr Anderson
		 ['name'] = 'Tempesta (S)',
		 ['brand'] = 'PEGASSI',
		 ['model'] = 'tempestaes',
		 ['price'] = 256000,
		 ['category'] = 'sports',
		 ['hash'] = `tempestaes`,
		 ['shop'] = 'pdm', 
	 },
		 ['torerod'] = { 	 	-- Vanilla Edit Mr Anderson
		 ['name'] = 'Torero',
		 ['brand'] = 'PEGASSI',
		 ['model'] = 'torerod',
		 ['price'] = 256000,
		 ['category'] = 'sports',
		 ['hash'] = `torerod`,
		 ['shop'] = 'pdm', 
	 },
	 ['zr390 '] = { 	 	-- Vanilla Edit Mr Anderson
		 ['name'] = 'Zr390 ',
		 ['brand'] = 'Annis',
		 ['model'] = 'zr390 ',
		 ['price'] = 221000,
		 ['category'] = 'sports',
		 ['hash'] = `zr390 `,
		 ['shop'] = 'pdm',
	 },
	 ['zrgpr'] = { 	 	-- Vanilla Edit Mr Anderson
		 ['name'] = 'ZR (GPR)',
		 ['brand'] = 'Annis',
		 ['model'] = 'zrgpr',
		 ['price'] = 221000,
		 ['category'] = 'sports',
		 ['hash'] = `zrgpr `,
		 ['shop'] = 'pdm',
	 },
	-- Muscle --
		['deviant'] = {						---	DLC
		['name'] = 'Deviant',
		['brand'] = 'Schyster',
		['model'] = 'deviant',
		['price'] = 1820000,
		['category'] = 'muscle',
		['hash'] = `deviant`,
		['shop'] = 'pdm',
	},
		['vigeronew'] = { 	 	-- Vanilla Edit Mr Anderson
		 ['name'] = 'Vigero (SVR)',
		 ['brand'] = 'DECLASSE',
		 ['model'] = 'vigeronew',
		 ['price'] = 221000,
		 ['category'] = 'muscle',
		 ['hash'] = `vigeronew`,
		 ['shop'] = 'pdm',
	 },
		 ['tampar'] = { 	 	-- Vanilla Edit Mr Anderson
		 ['name'] = 'Tampa (R)',
		 ['brand'] = 'DECLASSE',
		 ['model'] = 'tampar',
		 ['price'] = 182000,
		 ['category'] = 'muscle',
		 ['hash'] = `tampar`,
		 ['shop'] = 'pdm',
	 },
		['gauntletctx'] = { 	 	-- Vanilla Edit Mr Anderson
		['name'] = 'Gauntlet (CTX)',
		['brand'] = 'Bravado',
		['model'] = 'gauntletctx',
		['price'] = 254000,
		['category'] = 'muscle',
		['hash'] = `gauntletctx`,
		['shop'] = 'pdm',
	 },
		['gauntlet6str'] = { 	 	-- Vanilla Edit Mr Anderson
		['name'] = 'Gauntlet (STR)',
		['brand'] = 'Bravado',
		['model'] = 'gauntlet6str',
		['price'] = 254000,
		['category'] = 'muscle',
		['hash'] = `gauntlet6str`,
		['shop'] = 'pdm',
	 },
		['buffalo4h'] = { 	 	-- Vanilla Edit Mr Anderson
		['name'] = 'Buffalo (S)',
		['brand'] = 'Bravado',
		['model'] = 'buffalo4h',
		['price'] = 234000,
		['category'] = 'muscle',
		['hash'] = `buffalo4h`,
		['shop'] = 'pdm',
	 },
		['dominator'] = {
		['name'] = 'Dominator',
		['brand'] = 'Vapid',
		['model'] = 'dominator',
		['price'] = 189500,
		['category'] = 'muscle',
		['hash'] = `dominator`,
		['shop'] = 'pdm',
	},
		['dominator3'] = {
		['name'] = 'Dominator GTX',
		['brand'] = 'Vapid',
		['model'] = 'dominator3',
		['price'] = 232000,
		['category'] = 'muscle',
		['hash'] = `dominator3`,
		['shop'] = 'pdm',
	},
		['dominator7'] = {							--DLC +set sv_enforceGameBuild 2372
		['name'] = 'Dominator ASP',
		['brand'] = 'Vapid',
		['model'] = 'dominator7',
		['price'] = 198000,
		['category'] = 'muscle',
		['hash'] = `dominator7`,
		['shop'] = 'pdm',
	},
		['dominator8'] = {							--DLC +set sv_enforceGameBuild 2372
		['name'] = 'Dominator GTT',
		['brand'] = 'Vapid',
		['model'] = 'dominator8',
		['price'] = 200000,
		['category'] = 'muscle',
		['hash'] = `dominator8`,
		['shop'] = 'pdm',
	},
		['dukes'] = {
		['name'] = 'Dukes',
		['brand'] = 'Imponte',
		['model'] = 'dukes',
		['price'] = 223500,
		['category'] = 'muscle',
		['hash'] = `dukes`,
		['shop'] = 'pdm',
	},
		['ellie'] = {
		['name'] = 'Ellie',
		['brand'] = 'Vapid',
		['model'] = 'ellie',
		['price'] = 222250,
		['category'] = 'muscle',
		['hash'] = `ellie`,
		['shop'] = 'pdm',
	},
		['faction2'] = {
		['name'] = 'Faction Rider',
		['brand'] = 'Willard',
		['model'] = 'faction2',
		['price'] = 198000,
		['category'] = 'muscle',
		['hash'] = `faction2`,
		['shop'] = 'pdm',
	},
		['gauntlet'] = {
		['name'] = 'Gauntlet',
		['brand'] = 'Bravado',
		['model'] = 'gauntlet',
		['price'] = 189500,
		['category'] = 'muscle',
		['hash'] = `gauntlet`,
		['shop'] = 'pdm',
	},
		['gauntlet3'] = {						--	DLC
		['name'] = 'Classic Gauntlet',
		['brand'] = 'Bravado',
		['model'] = 'gauntlet3',
		['price'] = 225000,
		['category'] = 'muscle',
		['hash'] = `gauntlet3`,
		['shop'] = 'pdm',
	},
		['gauntlet4'] = {						--	DLC
		['name'] = 'Gauntlet Hellfire',
		['brand'] = 'Bravado',
		['model'] = 'gauntlet4',
		['price'] = 235000,
		['category'] = 'muscle',
		['hash'] = `gauntlet4`,
		['shop'] = 'pdm',
	},
		['gauntlet5'] = {
		['name'] = 'Gauntlet Classic Custom',
		['brand'] = 'Bravado',
		['model'] = 'gauntlet5',
		['price'] = 225000,
		['category'] = 'muscle',
		['hash'] = `gauntlet5`,
		['shop'] = 'pdm',
	},
		['hermes'] = {
		['name'] = 'Hermes',
		['brand'] = 'Albany',
		['model'] = 'hermes',
		['price'] = 235000,
		['category'] = 'muscle',
		['hash'] = `hermes`,
		['shop'] = 'pdm',
	},
		['hotknife'] = {
		['name'] = 'Hotknife',
		['brand'] = 'Vapid',
		['model'] = 'hotknife',
		['price'] = 235000,
		['category'] = 'muscle',
		['hash'] = `hotknife`,
		['shop'] = 'pdm',
	},
		['ruiner'] = {
		['name'] = 'Ruiner',
		['brand'] = 'Imponte',
		['model'] = 'ruiner',
		['price'] = 189000,
		['category'] = 'muscle',
		['hash'] = `ruiner`,
		['shop'] = 'pdm',
	},
		['sabregt'] = {
		['name'] = 'Sabre Turbo',
		['brand'] = 'Declasse',
		['model'] = 'sabregt',
		['price'] = 183000,
		['category'] = 'muscle',
		['hash'] = `sabregt`,
		['shop'] = 'pdm',
	},
		['vamos'] = {						--	DLC
		['name'] = 'Vamos',
		['brand'] = 'Declasse',
		['model'] = 'vamos',
		['price'] = 183000,
		['category'] = 'muscle',
		['hash'] = `vamos`,
		['shop'] = 'pdm',
	},
	-- Super --
		['infernus2'] = {
		['name'] = 'Infernus Classic',
		['brand'] = 'Pegassi',
		['model'] = 'infernus2',
		['price'] = 534000,
		['category'] = 'super',
		['hash'] = `infernus2`,
		['shop'] = 'luxury',
	},
		['turismo2'] = {
		['name'] = 'Turismo Classic',
		['brand'] = 'Grotti',
		['model'] = 'turismo2',
		['price'] = 554000,
		['category'] = 'super',
		['hash'] = `turismo2`,
		['shop'] = 'luxury',
	},
		['coquette4'] = {
		['name'] = 'Coquette D10',
		['brand'] = 'Invetero',
		['model'] = 'coquette4',
		['price'] = 562000,
		['category'] = 'super',
		['hash'] = `coquette4`,
		['shop'] = 'luxury',
	},
		['italirsx'] = {
		['name'] = 'Itali RSX',
		['brand'] = 'Progen',
		['model'] = 'italirsx',
		['price'] = 560000,
		['category'] = 'super',
		['hash'] = `italirsx`,
		['shop'] = 'luxury',
	},
		['adder'] = {
		['name'] = 'Adder',
		['brand'] = 'Truffade',
		['model'] = 'adder',
		['price'] = 486000,
		['category'] = 'super',
		['hash'] = `adder`,
		['shop'] = 'luxury',
	},
		['autarch'] = {
		['name'] = 'Autarch',
		['brand'] = 'Överflöd',
		['model'] = 'autarch',
		['price'] = 574000,
		['category'] = 'super',
		['hash'] = `autarch`,
		['shop'] = 'luxury',
	},
		['banshee2'] = {
		['name'] = 'Banshee 900R',
		['brand'] = 'Bravado',
		['model'] = 'banshee2',
		['price'] = 542000,
		['category'] = 'sports',
		['hash'] = `banshee2`,
		['shop'] = 'luxury',
	},
		['emerus'] = {						--	DLC
		['name'] = 'Emerus',
		['brand'] = 'Progen',
		['model'] = 'emerus',
		['price'] = 560000,
		['category'] = 'super',
		['hash'] = `emerus`,
		['shop'] = 'luxury',
	},
		['entity2'] = {
		['name'] = 'Entity XXR',
		['brand'] = 'Överflöd',
		['model'] = 'entity2',
		['price'] = 564000,
		['category'] = 'super',
		['hash'] = `entity2`,
		['shop'] = 'luxury',
	},
		['furia'] = {
		['name'] = 'Furia',
		['brand'] = 'Grotti',
		['model'] = 'furia',
		['price'] = 532000,
		['category'] = 'super',
		['hash'] = `furia`,
		['shop'] = 'luxury',
	},
		['italigtb2'] = {
		['name'] = 'Itali GTB',
		['brand'] = 'Progen',
		['model'] = 'italigtb2',
		['price'] = 562000,
		['category'] = 'super',
		['hash'] = `italigtb2`,
		['shop'] = 'luxury',
	},
		['nero2'] = {
		['name'] = 'Nero Custom',
		['brand'] = 'Truffade',
		['model'] = 'nero2',
		['price'] = 560000,
		['category'] = 'super',
		['hash'] = `nero2`,
		['shop'] = 'luxury',
	},
		['sc1'] = {
		['name'] = 'SC1',
		['brand'] = 'Übermacht',
		['model'] = 'sc1',
		['price'] = 590000,
		['category'] = 'super',
		['hash'] = `sc1`,
		['shop'] = 'luxury',
	},
		['tempesta'] = {
		['name'] = 'Tempesta',
		['brand'] = 'Pegassi',
		['model'] = 'tempesta',
		['price'] = 540000,
		['category'] = 'super',
		['hash'] = `tempesta`,
		['shop'] = 'luxury',
	},
		['tezeract'] = {
		['name'] = 'Tezeract',
		['brand'] = 'Pegassi',
		['model'] = 'tezeract',
		['price'] = 582000,
		['category'] = 'super',
		['hash'] = `tezeract`,
		['shop'] = 'luxury',
	},
		['thrax'] = {					--		DLC
		['name'] = 'Thrax',
		['brand'] = 'Truffade',
		['model'] = 'thrax',
		['price'] = 532000,
		['category'] = 'super',
		['hash'] = `thrax`,
		['shop'] = 'luxury',
	},
		['xa21'] = {
		['name'] = 'XA21',
		['brand'] = 'Ocelot',
		['model'] = 'xa21',
		['price'] = 568000,
		['category'] = 'super',
		['hash'] = `xa21`,
		['shop'] = 'luxury',
	},
		['zentorno'] = {
		['name'] = 'Zentorno',
		['brand'] = 'Pegassi',
		['model'] = 'zentorno',
		['price'] = 571000,
		['category'] = 'super',
		['hash'] = `zentorno`,
		['shop'] = 'luxury',
	},
		['severo'] = {
		['name'] = 'Severo',
		['brand'] = 'Pegassi',
		['model'] = 'severo',
		['price'] = 571000,
		['category'] = 'super',
		['hash'] = `severo`,
		['shop'] = 'luxury',
	},
	-- Motorcycles --
	['akuma'] = {
		['name'] = 'Akuma',
		['brand'] = 'Dinka',
		['model'] = 'akuma',
		['price'] = 55000,
		['category'] = 'motorcycles',
		['hash'] = `akuma`,
		['shop'] = 'pdm',
	},
	['avarus'] = {
		['name'] = 'Avarus',
		['brand'] = 'LCC',
		['model'] = 'avarus',
		['price'] = 20000,
		['category'] = 'motorcycles',
		['hash'] = `avarus`,
		['shop'] = 'pdm',
	},
	['bagger'] = {
		['name'] = 'Bagger',
		['brand'] = 'WMC',
		['model'] = 'bagger',
		['price'] = 13500,
		['category'] = 'motorcycles',
		['hash'] = `bagger`,
		['shop'] = 'pdm',
	},
	['bati'] = {
		['name'] = 'Bati 801',
		['brand'] = 'Pegassi',
		['model'] = 'bati',
		['price'] = 24000,
		['category'] = 'motorcycles',
		['hash'] = `bati`,
		['shop'] = 'pdm',
	},
	['bati2'] = {
		['name'] = 'Bati 801RR',
		['brand'] = 'Pegassi',
		['model'] = 'bati2',
		['price'] = 19000,
		['category'] = 'motorcycles',
		['hash'] = `bati2`,
		['shop'] = 'pdm',
	},
	['bf400'] = {
		['name'] = 'BF400',
		['brand'] = 'Nagasaki',
		['model'] = 'bf400',
		['price'] = 22000,
		['category'] = 'motorcycles',
		['hash'] = `bf400`,
		['shop'] = 'pdm',
	},
	['carbonrs'] = {
		['name'] = 'Carbon RS',
		['brand'] = 'Nagasaki',
		['model'] = 'carbonrs',
		['price'] = 22000,
		['category'] = 'motorcycles',
		['hash'] = `carbonrs`,
		['shop'] = 'pdm',
	},
	['chimera'] = {
		['name'] = 'Chimera',
		['brand'] = 'Nagasaki',
		['model'] = 'chimera',
		['price'] = 21000,
		['category'] = 'motorcycles',
		['hash'] = `chimera`,
		['shop'] = 'pdm',
	},
	['cliffhanger'] = {
		['name'] = 'Cliffhanger',
		['brand'] = 'Western',
		['model'] = 'cliffhanger',
		['price'] = 28500,
		['category'] = 'motorcycles',
		['hash'] = `cliffhanger`,
		['shop'] = 'pdm',
	},
	['daemon'] = {
		['name'] = 'Daemon',
		['brand'] = 'WMC',
		['model'] = 'daemon',
		['price'] = 14000,
		['category'] = 'motorcycles',
		['hash'] = `daemon`,
		['shop'] = 'pdm',
	},
	['daemon2'] = {
		['name'] = 'Daemon Custom',
		['brand'] = 'Western',
		['model'] = 'daemon2',
		['price'] = 23000,
		['category'] = 'motorcycles',
		['hash'] = `daemon2`,
		['shop'] = 'pdm',
	},
	['defiler'] = {
		['name'] = 'Defiler',
		['brand'] = 'Shitzu',
		['model'] = 'defiler',
		['price'] = 30000,
		['category'] = 'motorcycles',
		['hash'] = `defiler`,
		['shop'] = 'pdm',
	},
	['deathbike'] = {							--DLC
		['name'] = 'deathbike',
		['brand'] = 'deathbike',
		['model'] = 'deathbike',
		['price'] = 30000,
		['category'] = 'motorcycles',
		['hash'] = `deathbike`,
		['shop'] = 'pdm',
	},
	['deathbike2'] = {							--DLC
		['name'] = 'deathbike2',
		['brand'] = 'deathbike',
		['model'] = 'deathbike2',
		['price'] = 30000,
		['category'] = 'motorcycles',
		['hash'] = `deathbike2`,
		['shop'] = 'pdm',
	},
	['deathbike3'] = {							--DLC
		['name'] = 'deathbike3',
		['brand'] = 'deathbike',
		['model'] = 'deathbike3',
		['price'] = 30000,
		['category'] = 'motorcycles',
		['hash'] = `deathbike3`,
		['shop'] = 'pdm',
	},
	['diablous'] = {
		['name'] = 'Diablous',
		['brand'] = 'Principe',
		['model'] = 'diablous',
		['price'] = 30000,
		['category'] = 'motorcycles',
		['hash'] = `diablous`,
		['shop'] = 'pdm',
	},
	['diablous2'] = {
		['name'] = 'Diablous Custom',
		['brand'] = 'Principe',
		['model'] = 'diablous2',
		['price'] = 38000,
		['category'] = 'motorcycles',
		['hash'] = `diablous2`,
		['shop'] = 'pdm',
	},
	['double'] = {
		['name'] = 'Double-T',
		['brand'] = 'Dinka',
		['model'] = 'double',
		['price'] = 28000,
		['category'] = 'motorcycles',
		['hash'] = `double`,
		['shop'] = 'pdm',
	},
	['enduro'] = {
		['name'] = 'Enduro',
		['brand'] = 'Dinka',
		['model'] = 'enduro',
		['price'] = 5500,
		['category'] = 'motorcycles',
		['hash'] = `enduro`,
		['shop'] = 'pdm',
	},
	['esskey'] = {
		['name'] = 'Esskey',
		['brand'] = 'Pegassi',
		['model'] = 'esskey',
		['price'] = 12000,
		['category'] = 'motorcycles',
		['hash'] = `esskey`,
		['shop'] = 'pdm',
	},
	['faggio'] = {
		['name'] = 'Faggio Sport',
		['brand'] = 'Pegassi',
		['model'] = 'faggio',
		['price'] = 2000,
		['category'] = 'motorcycles',
		['hash'] = `faggio`,
		['shop'] = 'pdm',
	},
	['faggio2'] = {
		['name'] = 'Faggio',
		['brand'] = 'Pegassi',
		['model'] = 'faggio2',
		['price'] = 1900,
		['category'] = 'motorcycles',
		['hash'] = `faggio2`,
		['shop'] = 'pdm',
	},
	['faggio3'] = {
		['name'] = 'Faggio Mod',
		['brand'] = 'Pegassi',
		['model'] = 'faggio3',
		['price'] = 2500,
		['category'] = 'motorcycles',
		['hash'] = `faggio3`,
		['shop'] = 'pdm',
	},
	['fcr'] = {
		['name'] = 'FCR 1000',
		['brand'] = 'Pegassi',
		['model'] = 'fcr',
		['price'] = 5000,
		['category'] = 'motorcycles',
		['hash'] = `fcr`,
		['shop'] = 'pdm',
	},
	['fcr2'] = {
		['name'] = 'FCR 1000 Custom',
		['brand'] = 'Pegassi',
		['model'] = 'fcr2',
		['price'] = 19000,
		['category'] = 'motorcycles',
		['hash'] = `fcr2`,
		['shop'] = 'pdm',
	},
	['gargoyle'] = {
		['name'] = 'Gargoyle',
		['brand'] = 'Western',
		['model'] = 'gargoyle',
		['price'] = 32000,
		['category'] = 'motorcycles',
		['hash'] = `gargoyle`,
		['shop'] = 'pdm',
	},
	['hakuchou'] = {
		['name'] = 'Hakuchou',
		['brand'] = 'Shitzu',
		['model'] = 'hakuchou',
		['price'] = 17000,
		['category'] = 'motorcycles',
		['hash'] = `hakuchou`,
		['shop'] = 'pdm',
	},
	['hakuchou2'] = {
		['name'] = 'Hakuchou Drag',
		['brand'] = 'Shitzu',
		['model'] = 'hakuchou2',
		['price'] = 45000,
		['category'] = 'motorcycles',
		['hash'] = `hakuchou2`,
		['shop'] = 'pdm',
	},
	['hexer'] = {
		['name'] = 'Hexer',
		['brand'] = 'LCC',
		['model'] = 'hexer',
		['price'] = 16000,
		['category'] = 'motorcycles',
		['hash'] = `hexer`,
		['shop'] = 'pdm',
	},
	['innovation'] = {
		['name'] = 'Innovation',
		['brand'] = 'LLC',
		['model'] = 'innovation',
		['price'] = 33500,
		['category'] = 'motorcycles',
		['hash'] = `innovation`,
		['shop'] = 'pdm',
	},
	['lectro'] = {
		['name'] = 'Lectro',
		['brand'] = 'Principe',
		['model'] = 'lectro',
		['price'] = 28000,
		['category'] = 'motorcycles',
		['hash'] = `lectro`,
		['shop'] = 'pdm',
	},
	['manchez'] = {
		['name'] = 'Manchez',
		['brand'] = 'Maibatsu',
		['model'] = 'manchez',
		['price'] = 8300,
		['category'] = 'motorcycles',
		['hash'] = `manchez`,
		['shop'] = 'pdm',
	},
	['nemesis'] = {
		['name'] = 'Nemesis',
		['brand'] = 'Principe',
		['model'] = 'nemesis',
		['price'] = 20000,
		['category'] = 'motorcycles',
		['hash'] = `nemesis`,
		['shop'] = 'pdm',
	},
	['nightblade'] = {
		['name'] = 'Nightblade',
		['brand'] = 'WMC',
		['model'] = 'nightblade',
		['price'] = 23000,
		['category'] = 'motorcycles',
		['hash'] = `nightblade`,
		['shop'] = 'pdm',
	},
	['oppressor'] = {
		['name'] = 'Oppressor',
		['brand'] = 'Pegassi',
		['model'] = 'oppressor',
		['price'] = 9999999,
		['category'] = 'super',
		['hash'] = `oppressor`,
		['shop'] = 'luxury',
	},
	['pcj'] = {
		['name'] = 'PCJ-600',
		['brand'] = 'Shitzu',
		['model'] = 'pcj',
		['price'] = 15000,
		['category'] = 'motorcycles',
		['hash'] = `pcj`,
		['shop'] = 'pdm',
	},
	['ratbike'] = {
		['name'] = 'Rat Bike',
		['brand'] = 'Western',
		['model'] = 'ratbike',
		['price'] = 3000,
		['category'] = 'motorcycles',
		['hash'] = `ratbike`,
		['shop'] = 'pdm',
	},
	['ruffian'] = {
		['name'] = 'Ruffian',
		['brand'] = 'Pegassi',
		['model'] = 'ruffian',
		['price'] = 25000,
		['category'] = 'motorcycles',
		['hash'] = `ruffian`,
		['shop'] = 'pdm',
	},
	['sanchez'] = {
		['name'] = 'Sanchez Livery',
		['brand'] = 'Maibatsu',
		['model'] = 'sanchez',
		['price'] = 5300,
		['category'] = 'motorcycles',
		['hash'] = `sanchez`,
		['shop'] = 'pdm',
	},
	['sanchez2'] = {
		['name'] = 'Sanchez',
		['brand'] = 'Maibatsu',
		['model'] = 'sanchez2',
		['price'] = 5300,
		['category'] = 'motorcycles',
		['hash'] = `sanchez2`,
		['shop'] = 'pdm',
	},
	['sanctus'] = {
		['name'] = 'Sanctus',
		['brand'] = 'LCC',
		['model'] = 'sanctus',
		['price'] = 35000,
		['category'] = 'motorcycles',
		['hash'] = `sanctus`,
		['shop'] = 'pdm',
	},
	['shotaro'] = {
		['name'] = 'Shotaro Concept',
		['brand'] = 'Nagasaki',
		['model'] = 'shotaro',
		['price'] = 320000,
		['category'] = 'motorcycles',
		['hash'] = `shotaro`,
		['shop'] = 'pdm',
	},
	['sovereign'] = {
		['name'] = 'Sovereign',
		['brand'] = 'WMC',
		['model'] = 'sovereign',
		['price'] = 8000,
		['category'] = 'motorcycles',
		['hash'] = `sovereign`,
		['shop'] = 'pdm',
	},
	['stryder'] = {
		['name'] = 'Stryder',
		['brand'] = 'Nagasaki',
		['model'] = 'stryder',
		['price'] = 50000,
		['category'] = 'motorcycles',
		['hash'] = `stryder`,
		['shop'] = 'pdm',
	},
	['thrust'] = {
		['name'] = 'Thrust',
		['brand'] = 'Dinka',
		['model'] = 'thrust',
		['price'] = 22000,
		['category'] = 'motorcycles',
		['hash'] = `thrust`,
		['shop'] = 'pdm',
	},
	['vader'] = {
		['name'] = 'Vader',
		['brand'] = 'Shitzu',
		['model'] = 'vader',
		['price'] = 7200,
		['category'] = 'motorcycles',
		['hash'] = `vader`,
		['shop'] = 'pdm',
	},
	['vindicator'] = {
		['name'] = 'Vindicator',
		['brand'] = 'Dinka',
		['model'] = 'vindicator',
		['price'] = 19000,
		['category'] = 'motorcycles',
		['hash'] = `vindicator`,
		['shop'] = 'pdm',
	},
	['vortex'] = {
		['name'] = 'Vortex',
		['brand'] = 'Pegassi',
		['model'] = 'vortex',
		['price'] = 31000,
		['category'] = 'motorcycles',
		['hash'] = `vortex`,
		['shop'] = 'pdm',
	},
	['wolfsbane'] = {
		['name'] = 'Wolfsbane',
		['brand'] = 'Western',
		['model'] = 'wolfsbane',
		['price'] = 14000,
		['category'] = 'motorcycles',
		['hash'] = `wolfsbane`,
		['shop'] = 'pdm',
	},
	['zombiea'] = {
		['name'] = 'Zombie Bobber',
		['brand'] = 'Western',
		['model'] = 'zombiea',
		['price'] = 28000,
		['category'] = 'motorcycles',
		['hash'] = `zombiea`,
		['shop'] = 'pdm',
	},
	['zombieb'] = {
		['name'] = 'Zombie Chopper',
		['brand'] = 'Western',
		['model'] = 'zombieb',
		['price'] = 27000,
		['category'] = 'motorcycles',
		['hash'] = `zombieb`,
		['shop'] = 'pdm',
	},
	['manchez2'] = {
		['name'] = 'Manchez',
		['brand'] = 'Maibatsu',
		['model'] = 'manchez2',
		['price'] = 14000,
		['category'] = 'motorcycles',
		['hash'] = `manchez2`,
		['shop'] = 'pdm',
	},
	['shinobi'] = {		--DLC +set sv_enforceGameBuild 2545
		['name'] = 'Shinobi',
		['brand'] = 'Nagasaki',
		['model'] = 'shinobi',
		['price'] = 25000,
		['category'] = 'motorcycles',
		['hash'] = `shinobi`,
		['shop'] = 'pdm',
	},
	['reever'] = {		--DLC +set sv_enforceGameBuild 2545
		['name'] = 'Reever',
		['brand'] = 'Western',
		['model'] = 'reever',
		['price'] = 25000,
		['category'] = 'motorcycles',
		['hash'] = `reever`,
		['shop'] = 'pdm',
	},
	-- OFF ROAD --
	['blazer'] = {
		['name'] = 'Blazer',
		['brand'] = 'Annis',
		['model'] = 'blazer',
		['price'] = 15000,
		['category'] = 'offroad',
		['hash'] = `blazer`,
		['shop'] = 'pdm',
	},
	['brawler'] = {
		['name'] = 'Brawler',
		['brand'] = 'Annis',
		['model'] = 'brawler',
		['price'] = 40000,
		['category'] = 'offroad',
		['hash'] = `brawler`,
		['shop'] = 'pdm',
	},
	['caracara2'] = {							--DLC
		['name'] = 'Caracara 4x4',
		['brand'] = 'Vapid',
		['model'] = 'caracara2',
		['price'] = 146000,
		['category'] = 'offroad',
		['hash'] = `caracara2`,
		['shop'] = 'pdm',
	},
	['dune'] = {
		['name'] = 'Dune Buggy',
		['brand'] = 'Annis',
		['model'] = 'dune',
		['price'] = 34000,
		['category'] = 'offroad',
		['hash'] = `dune`,
		['shop'] = 'pdm',
	},
	['everon'] = {
		['name'] = 'Everon',
		['brand'] = 'Karin',
		['model'] = 'everon',
		['price'] = 147000,
		['category'] = 'offroad',
		['hash'] = `everon`,
		['shop'] = 'pdm',
	},
	['kamacho'] = {
		['name'] = 'Kamacho',
		['brand'] = 'Canis',
		['model'] = 'kamacho',
		['price'] = 162000,
		['category'] = 'offroad',
		['hash'] = `kamacho`,
		['shop'] = 'pdm',
	},
	['riata'] = {
		['name'] = 'Riata',
		['brand'] = 'Vapid',
		['model'] = 'riata',
		['price'] = 138000,
		['category'] = 'offroad',
		['hash'] = `riata`,
		['shop'] = 'pdm',
	},
	['sandking'] = {
		['name'] = 'Sandking',
		['brand'] = 'Annis',
		['model'] = 'sandking',
		['price'] = 148000,
		['category'] = 'offroad',
		['hash'] = `sandking`,
		['shop'] = 'pdm',
	},
	-- Vans --
		['nspeedo'] = {
		['name'] = 'Speedo',
		['brand'] = 'vapid',
		['model'] = 'nspeedo',
		['price'] = 9500,
		['category'] = 'van',
		['hash'] = `nspeedo`,
		['shop'] = 'pdm',
	},
	['gburrito2'] = {
		['name'] = 'Speedo',
		['brand'] = 'Declasse',
		['model'] = 'gburrito2',
		['price'] = 10000,
		['category'] = 'van',
		['hash'] = `gburrito2`,
		['shop'] = 'pdm',
	},
	['journey'] = {
		['name'] = 'Caravan',
		['brand'] = 'Zinconium',
		['model'] = 'journey',
		['price'] = 15000,
		['category'] = 'van',
		['hash'] = `journey`,
		['shop'] = 'pdm',
	},
		['rumpo'] = {
		['name'] = 'Rumpo',
		['brand'] = 'bravado',
		['model'] = 'rumpo',
		['price'] = 9000,
		['category'] = 'van',
		['hash'] = `rumpo`,
		['shop'] = 'pdm',
	},
	['rumpo3'] = {
		['name'] = 'Rumpo 4X4',
		['brand'] = 'bravado',
		['model'] = 'rumpo3',
		['price'] = 16000,
		['category'] = 'van',
		['hash'] = `rumpo3`,
		['shop'] = 'pdm',
	},
	['speedo'] = {
		['name'] = 'Speedo',
		['brand'] = 'bravado',
		['model'] = 'speedo',
		['price'] = 16000,
		['category'] = 'van',
		['hash'] = `speedo`,
		['shop'] = 'pdm',
	},
	['surfer'] = {
		['name'] = 'Surfer',
		['brand'] = 'bravado',
		['model'] = 'surfer',
		['price'] = 16000,
		['category'] = 'van',
		['hash'] = `surfer`,
		['shop'] = 'pdm',
	},
	-- ILLEGAL --
	['dune4'] = {
		['name'] = 'Ramper',
		['brand'] = 'Annis',
		['price'] = 804000,
		['category'] = 'illegal',
		['model'] = 'dune4',
		['hash'] = `dune4`,
		['shop'] = 'illegal',
	},
		['nightshark'] = {
		['name'] = 'Nightshade',
		['brand'] = 'Imponte',
		['model'] = 'nightshark',
		['price'] = 700000,
		['category'] = 'illegal',
		['hash'] = `nightshark`,
		['shop'] = 'illegal',
	},
		['outlaw'] = {
		['name'] = 'Outlaw',
		['brand'] = 'Nagasaki',
		['model'] = 'outlaw',
		['price'] = 515000,
		['category'] = 'illegal',
		['hash'] = `outlaw`,
		['shop'] = 'illegal',
	},
		['vagrant'] = {
		['name'] = 'Vagrant',
		['brand'] = 'Maxwell',
		['price'] = 610000,
		['category'] = 'illegal',
		['model'] = 'vagrant',
		['hash'] = `vagrant`,
		['shop'] = 'illegal',
	},
		['trophytruck2'] = {
		['name'] = 'Trophy Truck Limited',
		['brand'] = 'Annis',
		['price'] = 280000,
		['category'] = 'illegal',
		['model'] = 'trophytruck2',
		['hash'] = `trophytruck2`,
		['shop'] = 'illegal',
	},
		['zhaba'] = {
		['name'] = 'Mini Tank',
		['brand'] = 'Annis',
		['price'] = 1100000,
		['category'] = 'illegal',
		['model'] = 'zhaba',
		['hash'] = `zhaba`,
		['shop'] = 'illegal',
	},
		['wastelander'] = {
		['name'] = 'Mini Tank',
		['brand'] = 'Annis',
		['price'] = 2100000,
		['category'] = 'illegal',
		['model'] = 'wastelander',
		['hash'] = `wastelander`,
		['shop'] = 'illegal',
	},
		['vortex2'] = { 	 	-- Vanilla Edit Mr Anderson
		 ['name'] = 'Vortex',
		 ['brand'] = 'NAGASAKI',
		 ['model'] = 'vortex2',
		 ['price'] = 221000,
		 ['category'] = 'illegal',
		 ['hash'] = `vortex2 `,
		 ['shop'] = 'illegal',
	},
	-- police --
		['20charger'] = {
		['name'] = 'Hellcat PD',
		['brand'] = 'Dodge',
		['model'] = '20charger',
		['price'] = 30000,
		['category'] = 'police',
		['hash'] = `20charger`,
		['shop'] = 'police',
	},
		['scpd16'] = {
		['name'] = 'Camaro',
		['brand'] = 'Chevrolet',
		['model'] = 'scpd16',
		['price'] = 30000,
		['category'] = 'police',
		['hash'] = `scpd16`,
		['shop'] = 'police',
	},
		['gtr'] = {
		['name'] = 'Skyline GTR PD',
		['brand'] = 'Chevrolet',
		['model'] = 'gtr',
		['price'] = 30000,
		['category'] = 'police',
		['hash'] = `gtr`,
		['shop'] = 'police',
	},
		['scpd1'] = {
		['name'] = 'Crown Victoria',
		['brand'] = 'Ford',
		['model'] = 'scpd1',
		['price'] = 5000,
		['category'] = 'police',
		['hash'] = `scpd1`,
		['shop'] = 'police',
	},
		['scpd9'] = {
		['name'] = 'Crown Victoria UMK',
		['brand'] = 'Ford',
		['model'] = 'scpd9',
		['price'] = 10000,
		['category'] = 'police',	
		['hash'] = `scpd9`,
		['shop'] = 'police',
	},
		['scpd3'] = {
		['name'] = 'Charger PD',
		['brand'] = 'Dodge',
		['model'] = 'scpd3',
		['price'] = 10000,
		['category'] = 'police',
		['hash'] = `scpd3`,
		['shop'] = 'police',
	},
		['scpd10'] = {
		['name'] = 'Charger UMK PD',
		['brand'] = 'Dodge',
		['model'] = 'scpd10',
		['price'] = 5000,
		['category'] = 'police',
		['hash'] = `scpd10`,
		['shop'] = 'police',
	},
		['explorer'] = {
		['name'] = 'Explorer PD',
		['brand'] = 'Ford',
		['model'] = 'explorer',
		['price'] = 5000,
		['category'] = 'police',
		['hash'] = `explorer`,
		['shop'] = 'police',
	},
		['pdrover'] = {
		['name'] = 'Range Rover PD',
		['brand'] = 'Land Rover',
		['model'] = 'pdrover',
		['price'] = 30000,
		['category'] = 'police',
		['hash'] = `pdrover`,
		['shop'] = 'police',
	},
		['dvdt3'] = {
		['name'] = 'Dominator GTPD',
		['brand'] = 'Vapid',
		['model'] = 'dvdt3',
		['price'] = 30000,
		['category'] = 'police',
		['hash'] = `dvdt3`,
		['shop'] = 'police',
	},
	-- EMS --
	['emsnspeedo'] = {
		['name'] = 'Speedo EMS',
		['brand'] = 'Vapid',
		['model'] = 'emsnspeedo',
		['price'] = 5000,
		['category'] = 'EMS',
		['hash'] = `emsnspeedo`,
		['shop'] = 'EMS',
	},
	
	
		['ajwar'] = {
		['name'] = 'AJWAR',
		['brand'] = 'Rune',
		['model'] = 'ajwar',
		['price'] = 6300,
        ['category'] = 'compacts',
		['hash'] = `ajwar`,
        ['shop'] = 'pdm',
    },
		['chopin2'] = {
		['name'] = 'Chopin',
		['brand'] = 'Rune',
		['model'] = 'chopin2',
		['price'] = 6500,
		['category'] = 'compacts',
		['hash'] = `chopin2`,
        ['shop'] = 'pdm',
    },
		['dalia'] = {
		['name'] = 'Dalia',
		['brand'] = 'Vyssar',
		['model'] = 'dalia',
		['price'] = 6100,
		['category'] = 'compacts',
		['hash'] = `dalia`,
        ['shop'] = 'pdm',
    },
	['leo'] = {
		['name'] = 'Leo',
        ['brand'] = 'BF',
		['model'] = 'leo',
		['price'] = 7500,
		['category'] = 'compacts',
		['hash'] = `leo`,
        ['shop'] = 'pdm',
    },
}

for _, v in pairs(QBShared.Vehicles) do
	QBShared.VehicleHashes[v.hash] = v
end
